import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { Container, Nav, Navbar } from "react-bootstrap";

export default function Layout(props) {
  const router = useRouter();
  const { pathname } = router;

  const path =
    pathname.split("/")[1].charAt(0).toUpperCase() +
    pathname.split("/")[1].slice(1);

  return (
    <>
      <Head>
        <title>{path ? `${path} | ` : "Home | "}Frontend Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        bg="primary"
        expand="lg"
        variant="dark"
        className="shadow-sm py-3"
        fixed="top"
      >
        <Container>
          <Link href="/" passHref legacyBehavior>
            <Navbar.Brand className="fw-semibold">Synapsis.id</Navbar.Brand>
          </Link>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ms-auto gap-3" activeKey={pathname}>
              <Link href="/" passHref legacyBehavior>
                <Nav.Link>Home</Nav.Link>
              </Link>
              <Link href="/blogs" passHref legacyBehavior>
                <Nav.Link>Blogs</Nav.Link>
              </Link>
              <Link href="/users" passHref legacyBehavior>
                <Nav.Link>Users</Nav.Link>
              </Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>

      <Container className="mt-5 pt-5">{props.children}</Container>

      <footer className="py-3 mt-auto bg-dark">
        <p className="text-center text-light fs-6 m-0">
          Achmad Solehuddin - Frontend Developer Test @ Synapsis.id
        </p>
      </footer>
    </>
  );
}
